### ISSUE TITLE
Not working on some pages

### ISSUE THREAD

**Issue by mcbarin** [tomroyal/Make-America-Kittens-Again#1] opened 2016-12-27 22:59 UTC
I forked this couple of days ago (Thanks by the way, it works perfectly for people I've blacklisted :)) and one problem was as you can see, it doesn't work on domains with https since you've declared in your manifest file to work for only http. Why didn't you add https also, is there something i don't know behind that (since I'm not so familiar with JS and Chrome Extensions) or did you just miss it?

**Comment by tomroyal** [comment] 2017-01-01 09:29
Hi - this was by design, but outdated. When the plugin launched all the kitten images were on a server without https:// support, so to avoid mixed security warnings I set it to run only on http:// pages. Now the images are on S3, I can fix this in the next update (it's a one line change to the manifest file). Thanks!

**Comment by tomroyal** [comment] 2017-01-02 15:13
..and this is fixed in 1.1.1, out today. Thanks again.

**Closed by tomroyal** 2017-01-02 15:13 UTC
